version: "3.1"
services:
  app1-node-api:
    image: app1-node-ts-api:latest
    ports:
      - 3333:3333
    environment:
      - MONGO_CONNECT=mongodb://root:example@localhost:27017/admin
    command: yarn dev
    volumes:
      - ./:/app
    depends_on:
      - app1-node-mongodb

  app1-node-mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
