version: "3.1"
services:
  gocd-server:
    image: gocd/gocd-server:v19.12.0
    container_name: gocd-server
    ports:
      - 8153:8153
      - 8154:8154

  gocd-agent-python:
    image: gocd-agent-pytest:latest
    container_name: python-agent
    environment:
      - GO_SERVER_URL=https://gocd-server:8154/go
    depends_on:
      - gocd-server
