FROM gocd/gocd-agent-ubuntu-18.04:v19.12.0

USER root

RUN apt-get update

RUN echo "y" | apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN echo "y" | apt-get install nodejs

